app:
  name: "lmp"
  mode: "release"
  version: "v0.0.1"
  port: 8080
  machine_id: 1
  start_time: 2020-07-01

log:
  level: "debug"
  filename: "./lmp.log"
  max_size: 200
  max_backups: 7
  max_age: 67

influxdb:
  host: "127.0.0.1"
  port: 8086
  user: "root"
  password: "123456"
  dbname: "lmp"

plugin:
  path: "./plugins/"
  collecttime: 5

grafana:
  ip: "localhost:3000"

rabbitmq:
  host: "localhost"
  port: 5672
  mq_name: "proc_info_param"
  user: "guest"
  password: "guest"
  v_host: "/"

redis-cli:
  host: "localhost"
  port: 6379
  db_num: 0
  
clear_data:
  interval_day: 3
  check_interval: 10
  